### ISSUE TITLE
Should functionCallHandler in GetResponseFromChatbotAsyncWithFunctions return a `List<FunctionResult>`?

### ISSUE THREAD

**Issue by mikethea1** [lofcz/OpenAiNg#8]
Right now the handler is defined as `Func<List<FunctionCall>, Task<FunctionResult?>>`. This implies that a single `FunctionResult` can capture the results of multiple functions. However, I can't see how to do that via the API. I would have expected something like this:

```
Func<List<FunctionCall>, Task<List<FunctionResult>>>
```

That way if there are N calls I can return N results. Am I misunderstanding the intended usage pattern?

**Comment by lofcz** [comment]
You are correct, this will be fixed in the 3.0 version. If you need this now, I can fix and push another 3.0 beta later today.

**Comment by mikethea1** [comment]
It's holding me back from using that API, but I believe I can work around it by just not using conversations and instead constructing the sequence of `ChatRequests` manually.

**Comment by lofcz** [comment]
This is now fixed in f99b8f76bff309106e07e2a4f52d39514f3d6cb0, I've also changed `Conversation.OnAfterToolsCall` to be more intuitive. I intent to open-source a strongly typed function builder as a part of OpenAiNg soon, which should help with the functions further.

The new usage is here:
https://github.com/lofcz/OpenAiNg/blob/f99b8f76bff309106e07e2a4f52d39514f3d6cb0/OpenAiNg.Demo/ChatDemo.cs#L26-L71

**Comment by lofcz** [comment]
The fix is available in https://www.nuget.org/packages/OpenAiNg/3.0.0-beta2

**Comment by mikethea1** [comment]
Thanks!

**Comment by lofcz** [comment]
The API changed significantly in v3 update, sorry for the breaking changes! Updated example is in the readme.
